// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\pentek_dac_ip_test\DAC_NCO_4_ip_src_Pack_Complex_Vector.v
// Created: 2020-09-15 17:49:42
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DAC_NCO_4_ip_src_Pack_Complex_Vector
// Source Path: pentek_dac_ip_test/DAC_NCO_4xSampling_IQ/Pack Complex Vector
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DAC_NCO_4_ip_src_Pack_Complex_Vector
          (u_re_0,
           u_re_1,
           u_re_2,
           u_re_3,
           u_im_0,
           u_im_1,
           u_im_2,
           u_im_3,
           y);


  input   signed [15:0] u_re_0;  // sfix16_En15
  input   signed [15:0] u_re_1;  // sfix16_En15
  input   signed [15:0] u_re_2;  // sfix16_En15
  input   signed [15:0] u_re_3;  // sfix16_En15
  input   signed [15:0] u_im_0;  // sfix16_En15
  input   signed [15:0] u_im_1;  // sfix16_En15
  input   signed [15:0] u_im_2;  // sfix16_En15
  input   signed [15:0] u_im_3;  // sfix16_En15
  output  [127:0] y;  // ufix128




  DAC_NCO_4_ip_src_pack_vector_complex u_pack_vector_complex (.u_re_0(u_re_0),  // sfix16_En15
                                                              .u_re_1(u_re_1),  // sfix16_En15
                                                              .u_re_2(u_re_2),  // sfix16_En15
                                                              .u_re_3(u_re_3),  // sfix16_En15
                                                              .u_im_0(u_im_0),  // sfix16_En15
                                                              .u_im_1(u_im_1),  // sfix16_En15
                                                              .u_im_2(u_im_2),  // sfix16_En15
                                                              .u_im_3(u_im_3),  // sfix16_En15
                                                              .y(y)  // ufix128
                                                              );

endmodule  // DAC_NCO_4_ip_src_Pack_Complex_Vector

