// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\pentek_dac_ip_test\DAC_NCO_4_ip_src_For_Each_Subsystem.v
// Created: 2020-09-15 17:49:42
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DAC_NCO_4_ip_src_For_Each_Subsystem
// Source Path: pentek_dac_ip_test/DAC_NCO_4xSampling_IQ/Vector NCO/For Each Subsystem
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DAC_NCO_4_ip_src_For_Each_Subsystem
          (clk,
           reset,
           enb,
           inc,
           offset,
           dataOut_re,
           dataOut_im,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   [31:0] inc;  // uint32
  input   [31:0] offset;  // uint32
  output  signed [15:0] dataOut_re;  // sfix16_En15
  output  signed [15:0] dataOut_im;  // sfix16_En15
  output  validOut;


  wire Constant_out1;
  wire signed [15:0] NCO_HDL_Optimized4_out1_re;  // sfix16_En15
  wire signed [15:0] NCO_HDL_Optimized4_out1_im;  // sfix16_En15
  wire NCO_HDL_Optimized4_out2;


  assign Constant_out1 = 1'b1;



  DAC_NCO_4_ip_src_NCO_HDL_Optimized4 u_NCO_HDL_Optimized4 (.clk(clk),
                                                            .reset(reset),
                                                            .enb(enb),
                                                            .inc(inc),  // uint32
                                                            .offset(offset),  // uint32
                                                            .validIn(Constant_out1),
                                                            .complexexp_re(NCO_HDL_Optimized4_out1_re),  // sfix16_En15
                                                            .complexexp_im(NCO_HDL_Optimized4_out1_im),  // sfix16_En15
                                                            .validOut(NCO_HDL_Optimized4_out2)
                                                            );

  assign dataOut_re = NCO_HDL_Optimized4_out1_re;

  assign dataOut_im = NCO_HDL_Optimized4_out1_im;

  assign validOut = NCO_HDL_Optimized4_out2;

endmodule  // DAC_NCO_4_ip_src_For_Each_Subsystem

