// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\pentek_dac_ip_test\DAC_NCO_4_ip_src_pack_vector_complex.v
// Created: 2020-09-15 17:49:42
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DAC_NCO_4_ip_src_pack_vector_complex
// Source Path: pentek_dac_ip_test/DAC_NCO_4xSampling_IQ/Pack Complex Vector/pack_vector_complex
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DAC_NCO_4_ip_src_pack_vector_complex
          (u_re_0,
           u_re_1,
           u_re_2,
           u_re_3,
           u_im_0,
           u_im_1,
           u_im_2,
           u_im_3,
           y);


  input   signed [15:0] u_re_0;  // sfix16_En15
  input   signed [15:0] u_re_1;  // sfix16_En15
  input   signed [15:0] u_re_2;  // sfix16_En15
  input   signed [15:0] u_re_3;  // sfix16_En15
  input   signed [15:0] u_im_0;  // sfix16_En15
  input   signed [15:0] u_im_1;  // sfix16_En15
  input   signed [15:0] u_im_2;  // sfix16_En15
  input   signed [15:0] u_im_3;  // sfix16_En15
  output  [127:0] y;  // ufix128


  wire signed [15:0] u_re [0:3];  // sfix16_En15 [4]
  wire signed [15:0] u_im [0:3];  // sfix16_En15 [4]
  reg [127:0] y_1;  // ufix128
  reg signed [15:0] temp [0:7];  // sfix16_En15 [8]


  assign u_re[0] = u_re_0;
  assign u_re[1] = u_re_1;
  assign u_re[2] = u_re_2;
  assign u_re[3] = u_re_3;

  assign u_im[0] = u_im_0;
  assign u_im[1] = u_im_1;
  assign u_im[2] = u_im_2;
  assign u_im[3] = u_im_3;

  always @* begin
    // Interleave real/imag
    temp[7] = u_re[0];
    temp[6] = u_im[0];
    temp[5] = u_re[1];
    temp[4] = u_im[1];
    temp[3] = u_re[2];
    temp[2] = u_im[2];
    temp[1] = u_re[3];
    temp[0] = u_im[3];
    y_1 = {temp[0], temp[1], temp[2], temp[3], temp[4], temp[5], temp[6], temp[7]};
  end



  assign y = y_1;

endmodule  // DAC_NCO_4_ip_src_pack_vector_complex

