// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\pentek_dac_ip_test\DAC_NCO_4_ip_axi4_stream_slave.v
// Created: 2020-09-15 17:49:48
// 
// Generated by MATLAB 9.7 and HDL Coder 3.15
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: DAC_NCO_4_ip_axi4_stream_slave
// Source Path: DAC_NCO_4_ip/DAC_NCO_4_ip_axi4_stream_slave
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DAC_NCO_4_ip_axi4_stream_slave
          (clk,
           reset,
           enb,
           AXI4_Stream_Slave_TDATA,
           AXI4_Stream_Slave_TVALID,
           user_ready,
           AXI4_Stream_Slave_TREADY,
           user_data,
           user_valid);


  input   clk;
  input   reset;
  input   enb;
  input   [127:0] AXI4_Stream_Slave_TDATA;  // ufix128
  input   AXI4_Stream_Slave_TVALID;  // ufix1
  input   user_ready;  // ufix1
  output  AXI4_Stream_Slave_TREADY;  // ufix1
  output  [127:0] user_data;  // ufix128
  output  user_valid;  // ufix1


  reg  fifo_rd_ack;  // ufix1
  wire [127:0] stream_in_user_data;  // ufix128
  wire fifo_empty;  // ufix1
  wire fifo_full;  // ufix1
  wire fifo_empty_neg;  // ufix1
  wire stream_in_user_valid;  // ufix1


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        fifo_rd_ack <= 1'b0;
      end
      else begin
        if (enb) begin
          fifo_rd_ack <= user_ready;
        end
      end
    end



  DAC_NCO_4_ip_fifo_data u_DAC_NCO_4_ip_fifo_data_inst (.clk(clk),
                                                        .reset(reset),
                                                        .enb(enb),
                                                        .In(AXI4_Stream_Slave_TDATA),  // ufix128
                                                        .Push(AXI4_Stream_Slave_TVALID),  // ufix1
                                                        .Pop(fifo_rd_ack),  // ufix1
                                                        .Out(stream_in_user_data),  // ufix128
                                                        .Empty(fifo_empty),  // ufix1
                                                        .Full(fifo_full)  // ufix1
                                                        );

  assign AXI4_Stream_Slave_TREADY =  ~ fifo_full;



  assign user_data = stream_in_user_data;

  assign fifo_empty_neg =  ~ fifo_empty;



  assign stream_in_user_valid = fifo_empty_neg & fifo_rd_ack;



  assign user_valid = stream_in_user_valid;

endmodule  // DAC_NCO_4_ip_axi4_stream_slave

